name: deploy
on: [push]
jobs:
  build:
    name: DeployFe
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/frontend
          pm2 stop frontend
          git pull origin main
          npm install
          npm run build
          pm2 start frontend
